name: "tagged-release"
on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Install JDK"
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: "Build with Gradle"
        run: ./gradlew clean build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*.jar